# This file may not be shared/redistributed without permission. Please read copyright notice in the git repo. If this file contains other copyright notices disregard this text.
"""
This project resembles the Inventory-control problem discussed in (Her25, Subsection 5.1.2) but with more complicated rules.
If you are stuck, the inventory-control problem will be a good place to start.

I recommend to use the DP_stochastic function (as we did with the inventory-control example). This means
your main problem is to build appropriate DPModel-classes to represent the different problems.

References:
  [Her25] Tue Herlau. Sequential decision making. (Freely available online), 2025.
"""
from irlc.ex02.dp_model import DPModel
from irlc.ex02.dp import DP_stochastic
import matplotlib.pyplot as plt
from scipy.stats import binom
from irlc import savepdf
import numpy as np

def plot_policy(pi, title, pdf):
    """Helper function to plot the policy functions pi, as generated by the DP_stochastic function. This function
    can be used to visualize which actions are taken in which state (y-axis) at which time step (x-axis)."""
    N = len(pi)
    W = max(pi[0].keys())
    A = np.zeros((W, N))
    for i in range(W):
        for j in range(N):
            A[i, j] = pi[j][i]
    plt.imshow(A)
    plt.title(title)
    savepdf(pdf)
    plt.show()

# TODO: 51 lines missing.
#raise NotImplementedError("Insert your solution and remove this error.")

def warmup_states(): 
    return np.arange(0,20+1)

def warmup_actions(): 
    return np.arange(0,15+1)

def solve_kiosk_1():
    N = 14
    ns = 20
    no = 15
    c_o = 1.5
    s_p = 2.1

    P_w = {0: 0.3, 3: 0.6, 6: 0.1}

    S = list(range(ns + 1))

    J = [{} for _ in range(N + 1)]
    pi = [{} for _ in range(N)]

    for x_N in S:
        J[N][x_N] = 0.0

    for k in range(N - 1, -1, -1):
        for x_k in S:
            best_val = float("inf")
            best_u = None

            for u_k in range(no + 1):
                q = 0.0
                for w_k, p in P_w.items():
                    g_k = c_o * u_k - s_p * min(x_k + u_k, w_k)
                    x_k1 = min(ns, max(0, x_k + u_k - w_k))
                    q += p * (g_k + J[k + 1][x_k1])

                if q < best_val:
                    best_val = q
                    best_u = u_k

            J[k][x_k] = best_val
            pi[k][x_k] = best_u

    return J, pi

    # TODO: 1 lines missing.
    #raise NotImplementedError("Return cost and policy here (same format as DP_stochastic)")


def solve_kiosk_2():
    N = 14
    ns = 20
    no = 15
    c_o = 1.5
    s_p = 2.1
    p = 1/5

    P_w = {w: binom.pmf(w, ns, p) for w in range(ns + 1)}

    S = list(range(ns + 1))

    J = [{} for _ in range(N + 1)]
    pi = [{} for _ in range(N)]

    for x_N in S:
        J[N][x_N] = 0.0

    for k in range(N - 1, -1, -1):
        for x_k in S:
            best_val = float("inf")
            best_u = None

            for u_k in range(no + 1):
                q = 0.0
                for w_k, pw in P_w.items():
                    x_raw = x_k + u_k - w_k
                    x_k1 = min(ns, max(0, x_raw))
                    excess = max(0, x_raw - ns)
                    g_k = c_o * u_k - s_p * min(x_k + u_k, w_k) + 3 * excess
                    q += pw * (g_k + J[k + 1][x_k1])

                if q < best_val:
                    best_val = q
                    best_u = u_k

            J[k][x_k] = best_val
            pi[k][x_k] = best_u

    return J, pi

def main():
    # Problem 14
    print("Available states S_0:", warmup_states())
    print("Available actions A_0(x_0):", warmup_actions())

    J, pi = solve_kiosk_1() # Problem 16
    print("Kiosk1: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk1", "Latex/figures/kiosk1")
    plt.show()

    J, pi = solve_kiosk_2() # Problem 17
    print("Kiosk 2: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk2", "Latex/figures/kiosk2")
    plt.show()


if __name__ == "__main__":
    main()
