# This file may not be shared/redistributed without permission. Please read copyright notice in the git repo. If this file contains other copyright notices disregard this text.
"""
This project resembles the Inventory-control problem discussed in (Her25, Subsection 5.1.2) but with more complicated rules.
If you are stuck, the inventory-control problem will be a good place to start.

I recommend to use the DP_stochastic function (as we did with the inventory-control example). This means
your main problem is to build appropriate DPModel-classes to represent the different problems.

References:
  [Her25] Tue Herlau. Sequential decision making. (Freely available online), 2025.
"""
from irlc.ex02.dp_model import DPModel
from irlc.ex02.dp import DP_stochastic
import matplotlib.pyplot as plt
from scipy.stats import binom
from irlc import savepdf
import numpy as np

def plot_policy(pi, title, pdf):
    """Helper function to plot the policy functions pi, as generated by the DP_stochastic function. This function
    can be used to visualize which actions are taken in which state (y-axis) at which time step (x-axis)."""
    N = len(pi)
    W = max(pi[0].keys())
    A = np.zeros((W, N))
    for i in range(W):
        for j in range(N):
            A[i, j] = pi[j][i]
    plt.imshow(A)
    plt.title(title)
    savepdf(pdf)
    plt.show()

# TODO: 51 lines missing.
#raise NotImplementedError("Insert your solution and remove this error.")

class Kiosk1DPModel(DPModel):
    def __init__(self):
        self.N = 14
        self.ns = 20
        self.no = 15
        self.co = 1.5
        self.sp = 2.1
        self.Pw_dict = {0:0.3, 3:0.6, 6:0.1}
        super().__init__(N=self.N)

    def S(self, k):
        return set(range(self.ns + 1))

    def A(self, x, k):
        return set(range(self.no + 1))

    def Pw(self, x, u, k):
        return self.Pw_dict

    def f(self, x, u, w, k):
        return min(self.ns, max(0, x + u - w))

    def g(self, x, u, w, k):
        return self.co*u - self.sp*min(x+u, w)

    def gN(self, x):
        return 0
    
class Kiosk2DPModel(DPModel):
    def __init__(self):
        self.N = 14
        self.ns = 20
        self.no = 15
        self.co = 1.5
        self.sp = 2.1
        p = 1/5
        self.Pw_dict = {w: binom.pmf(w, self.ns, p) for w in range(self.ns+1)}
        super().__init__(N=self.N)

    def S(self, k):
        return set(range(self.ns + 1))

    def A(self, x, k):
        return set(range(self.no + 1))

    def Pw(self, x, u, k):
        return self.Pw_dict

    def f(self, x, u, w, k):
        x_raw = x + u - w
        return min(self.ns, max(0, x_raw))

    def g(self, x, u, w, k):
        x_pre = x + u - w
        excess = max(0, x_pre - self.ns)
        return self.co*u - self.sp*min(x+u, w) + 3*excess

    def gN(self, x):
        return 0

def warmup_states(): 
    return np.arange(0,20+1)

def warmup_actions(): 
    return np.arange(0,15+1)

def solve_kiosk_1():
    model = Kiosk1DPModel()
    return DP_stochastic(model)

def solve_kiosk_2():
    model = Kiosk2DPModel()
    return DP_stochastic(model)


def main():
    # Problem 14
    print("Available states S_0:", warmup_states())
    print("Available actions A_0(x_0):", warmup_actions())

    J, pi = solve_kiosk_1() # Problem 16
    print("Kiosk1: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk1", "Latex/figures/kiosk1")
    plt.show()

    J, pi = solve_kiosk_2() # Problem 17
    print("Kiosk 2: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk2", "Latex/figures/kiosk2")
    plt.show()


if __name__ == "__main__":
    main()
